export const wIcons = new Map([
    [800, ["sun", "night"]],
    [801, ["cloudy", "cloud (1)"]],
    [802, ["cloudy", "cloud (1)"]],
    [803, ["cloud", "cloud"]],
    [804, ["cloud", "cloud"]],
    [781, ["tornado (1)", "tornado (1)"]],
    [741, ["fog", "fog"]],
    [200, ["storm (1)", "storm (1)"]],
    [201, ["storm (1)", "storm (1)"]],
    [202, ["storm (1)", "storm (1)"]],
    [210, ["storm (1)", "storm (1)"]],
    [211, ["storm (1)", "storm (1)"]],
    [212, ["storm (1)", "storm (1)"]],
    [221, ["storm (1)", "storm (1)"]],
    [230, ["storm (1)", "storm (1)"]],
    [231, ["storm (1)", "storm (1)"]],
    [232, ["storm (1)", "storm (1)"]],
    [300, ["rainy_new", "rainy_new"]],
    [301, ["rainy_new", "rainy_new"]],
    [302, ["rainy_new", "rainy_new"]],
    [310, ["rainy_new", "rainy_new"]],
    [311, ["rainy_new", "rainy_new"]],
    [312, ["rainy_new", "rainy_new"]],
    [313, ["rainy_new", "rainy_new"]],
    [314, ["rainy_new", "rainy_new"]],
    [321, ["rainy_new", "rainy_new"]],
    [500, ["rainy_new", "rainy_new"]],
    [501, ["rainy_new", "rainy_new"]],
    [502, ["rainy_new", "rainy_new"]],
    [503, ["rainy_new", "rainy_new"]],
    [504, ["rainy_new", "rainy_new"]],
    [511, ["rainy_new", "rainy_new"]],
    [520, ["rainy_new", "rainy_new"]],
    [521, ["rainy_new", "rainy_new"]],
    [522, ["rainy_new", "rainy_new"]],
    [531, ["rainy_new", "rainy_new"]],
    [600, ["snowy", "snowy"]],
    [601, ["snowy", "snowy"]],
    [602, ["snowy", "snowy"]],
    [611, ["snowy", "snowy"]],
    [612, ["snowy", "snowy"]],
    [613, ["snowy", "snowy"]],
    [615, ["snowy", "snowy"]],
    [616, ["snowy", "snowy"]],
    [620, ["snowy", "snowy"]],
    [621, ["snowy", "snowy"]],
    [622, ["snowy", "snowy"]],
    [701, ["fog", "fog"]],
    [711, ["fog", "fog"]],
    [721, ["fog", "fog"]],
    [731, ["fog", "fog"]],
    [751, ["fog", "fog"]],
    [761, ["fog", "fog"]],
    [762, ["fog", "fog"]],
    [771, ["windy (1)", "windy (1)"]]
]);
